#include <xinu.h>
#include <test/fake.h>

DEFINE_FFF_GLOBALS;

void reset_fakes() {
  XIT_VALUE_FAKES(XIT_RESET);
  XIT_VOID_FAKES(XIT_RESET);
  FFF_RESET_HISTORY();
}

XIT_VALUE_FAKES(XIT_DEFN_VALUE_FAKE);
XIT_VOID_FAKES(XIT_DEFN_VOID_FAKE);
