#include <xinu.h>
#include <test/fake.h>

DEFINE_FFF_GLOBALS;

void reset_fakes() {
  FAKE_VALUE_FUNCTION_LIST(RESET_VALUE_FAKE);
  FAKE_VOID_FUNCTION_LIST(RESET_VOID_FAKE);
  FFF_RESET_HISTORY();
}

FAKE_VALUE_FUNCTION_LIST(DEFINE_FAKE_VALUE_FUNC);
FAKE_VOID_FUNCTION_LIST(DEFINE_FAKE_VOID_FUNC);
